/// Comprehensive 40-week clinical gestational development database.
/// Provides medical-grade benchmarks for weekly fetal dimensions, organ milestones,
/// maternal physiologic transitions, and relatable fruit/botanical size analogies.
class GestationalWeekInfo {
  final int week;
  final int trimester;
  final String babySizeFruit;
  final String babySizeComparison;
  final double estimatedLengthCm;
  final double estimatedWeightGrams;
  final String fetalMilestone;
  final String maternalChanges;
  final String clinicalTip;

  const GestationalWeekInfo({
    required this.week,
    required this.trimester,
    required this.babySizeFruit,
    required this.babySizeComparison,
    required this.estimatedLengthCm,
    required this.estimatedWeightGrams,
    required this.fetalMilestone,
    required this.maternalChanges,
    required this.clinicalTip,
  });

  /// Length in inches (formatted to 1 decimal place)
  double get estimatedLengthInches =>
      double.parse((estimatedLengthCm / 2.54).toStringAsFixed(1));

  /// Weight in ounces or pounds for intuitive maternal reference
  String get formattedWeightImperial {
    if (estimatedWeightGrams < 453.59) {
      final oz = (estimatedWeightGrams / 28.3495).toStringAsFixed(1);
      return '$oz oz';
    } else {
      final lbs = (estimatedWeightGrams / 453.59).toStringAsFixed(2);
      return '$lbs lbs';
    }
  }

  String get trimesterLabel {
    switch (trimester) {
      case 1:
        return 'First Trimester';
      case 2:
        return 'Second Trimester';
      case 3:
      default:
        return 'Third Trimester';
    }
  }
}

class GestationalDatabase {
  static final Map<int, GestationalWeekInfo> _data = {
    1: const GestationalWeekInfo(
      week: 1,
      trimester: 1,
      babySizeFruit: 'Microscopic Blastocyst',
      babySizeComparison: 'Conception phase • Cellular proliferation',
      estimatedLengthCm: 0.05,
      estimatedWeightGrams: 0.01,
      fetalMilestone: 'Fertilization and rapid cellular division in the fallopian tube.',
      maternalChanges: 'Uterine lining vascularizing in preparation for implantation.',
      clinicalTip: 'Ensure daily 400mcg folic acid supplementation to prevent neural tube defects.',
    ),
    2: const GestationalWeekInfo(
      week: 2,
      trimester: 1,
      babySizeFruit: 'Fertilized Ovum',
      babySizeComparison: 'Blastocyst cluster traveling to uterus (~0.1mm)',
      estimatedLengthCm: 0.08,
      estimatedWeightGrams: 0.02,
      fetalMilestone: 'Blastocyst begins nesting into the rich endometrial lining.',
      maternalChanges: 'Possible very light implantation spotting and mild pelvic sensation.',
      clinicalTip: 'Hydrate well and discontinue any alcohol or non-prescribed medications.',
    ),
    3: const GestationalWeekInfo(
      week: 3,
      trimester: 1,
      babySizeFruit: 'Poppy Seed',
      babySizeComparison: 'Small as a tiny poppy seed (~1mm)',
      estimatedLengthCm: 0.1,
      estimatedWeightGrams: 0.05,
      fetalMilestone: 'Embryonic disc differentiates into ectoderm, mesoderm, and endoderm.',
      maternalChanges: 'hCG hormone production surges; basal body temperature elevated.',
      clinicalTip: 'Home pregnancy tests can detect early hCG elevation around this time.',
    ),
    4: const GestationalWeekInfo(
      week: 4,
      trimester: 1,
      babySizeFruit: 'Sesame Seed',
      babySizeComparison: 'Size of a crisp sesame seed (~2mm)',
      estimatedLengthCm: 0.2,
      estimatedWeightGrams: 0.15,
      fetalMilestone: 'Neural tube and primitive heart tube establish basic circulation.',
      maternalChanges: 'Early breast sensitivity, fatigue, and heightened olfactory acuity.',
      clinicalTip: 'Schedule your first initial prenatal consultation with your OB/GYN or midwife.',
    ),
    5: const GestationalWeekInfo(
      week: 5,
      trimester: 1,
      babySizeFruit: 'Apple Seed',
      babySizeComparison: 'Size of an apple seed (~3.3mm)',
      estimatedLengthCm: 0.33,
      estimatedWeightGrams: 0.25,
      fetalMilestone: 'Primitive heart beats rhythmically at 100-120 contractions per minute.',
      maternalChanges: 'Morning nausea and mild fluid retention may begin emerging.',
      clinicalTip: 'Eat small, frequent protein-rich meals to stabilize blood sugar against nausea.',
    ),
    6: const GestationalWeekInfo(
      week: 6,
      trimester: 1,
      babySizeFruit: 'Sweet Pea',
      babySizeComparison: 'Size of a sweet green pea (~6mm)',
      estimatedLengthCm: 0.6,
      estimatedWeightGrams: 0.5,
      fetalMilestone: 'Optic vesicles and limb buds elongate; facial features begin to form.',
      maternalChanges: 'Progesterone levels surge; urinary frequency noticeably increases.',
      clinicalTip: 'Ginger tea and vitamin B6 can help soothe morning sickness naturally.',
    ),
    7: const GestationalWeekInfo(
      week: 7,
      trimester: 1,
      babySizeFruit: 'Blueberry',
      babySizeComparison: 'Size of a fresh blueberry (~1.3cm)',
      estimatedLengthCm: 1.3,
      estimatedWeightGrams: 1.0,
      fetalMilestone: 'Brain hemispheres dividing; arm and leg segments begin flexing.',
      maternalChanges: 'Uterus expands to the size of a lemon; cervix forms protective mucus plug.',
      clinicalTip: 'Wear a supportive, non-wired cotton bra to relieve chest discomfort.',
    ),
    8: const GestationalWeekInfo(
      week: 8,
      trimester: 1,
      babySizeFruit: 'Raspberry',
      babySizeComparison: 'Size of a ripe raspberry (~1.6cm)',
      estimatedLengthCm: 1.6,
      estimatedWeightGrams: 1.2,
      fetalMilestone: 'Webbed fingers and toes emerge; retinal pigment darkens in developing eyes.',
      maternalChanges: 'Blood volume increases by 10-15%; occasional mild headaches.',
      clinicalTip: 'Maintain optimal hydration: aim for 8-10 glasses of clean water daily.',
    ),
    9: const GestationalWeekInfo(
      week: 9,
      trimester: 1,
      babySizeFruit: 'Green Olive',
      babySizeComparison: 'Size of a green olive (~2.3cm)',
      estimatedLengthCm: 2.3,
      estimatedWeightGrams: 2.0,
      fetalMilestone: 'Major joints bend; essential organ systems are now fully established.',
      maternalChanges: 'Metabolic rate shifts upward; vivid pregnancy dreams and mood fluctuations.',
      clinicalTip: 'Practice gentle 15-minute walks to stimulate healthy venous blood return.',
    ),
    10: const GestationalWeekInfo(
      week: 10,
      trimester: 1,
      babySizeFruit: 'Prune',
      babySizeComparison: 'Size of a sweet prune (~3.1cm)',
      estimatedLengthCm: 3.1,
      estimatedWeightGrams: 4.0,
      fetalMilestone: 'Embryonic tail recedes completely; tiny fingernails and tooth buds form.',
      maternalChanges: 'Abdominal skin begins stretching; veining becomes visible across breasts.',
      clinicalTip: 'NIPT genetic screening blood panel is typically scheduled between weeks 10-12.',
    ),
    11: const GestationalWeekInfo(
      week: 11,
      trimester: 1,
      babySizeFruit: 'Lime',
      babySizeComparison: 'Size of a tangy green lime (~4.1cm)',
      estimatedLengthCm: 4.1,
      estimatedWeightGrams: 7.0,
      fetalMilestone: 'Bones begin ossifying; diaphragm matures as baby practices breathing hiccups.',
      maternalChanges: 'Nausea begins waning for many; hair and nail growth rate accelerates.',
      clinicalTip: 'Incorporate calcium and magnesium-rich foods (almonds, leafy greens, yogurt).',
    ),
    12: const GestationalWeekInfo(
      week: 12,
      trimester: 1,
      babySizeFruit: 'Plum',
      babySizeComparison: 'Size of a juicy plum (~5.4cm)',
      estimatedLengthCm: 5.4,
      estimatedWeightGrams: 14.0,
      fetalMilestone: 'Complex reflexes active: baby can open/close mouth and curl toes.',
      maternalChanges: 'End of First Trimester! Uterus lifts above pubic bone, relieving bladder.',
      clinicalTip: 'First-trimester nuchal translucency scan milestone is completed around now.',
    ),
    13: const GestationalWeekInfo(
      week: 13,
      trimester: 1,
      babySizeFruit: 'Meyer Lemon',
      babySizeComparison: 'Size of a Meyer lemon (~7.4cm)',
      estimatedLengthCm: 7.4,
      estimatedWeightGrams: 23.0,
      fetalMilestone: 'Vocal cords form; baby swallows small sips of amniotic fluid.',
      maternalChanges: 'Second trimester energy boost arrives; placenta fully takes over hormone regulation.',
      clinicalTip: 'Start pelvic floor Kegel conditioning exercises to prepare for delivery.',
    ),
    14: const GestationalWeekInfo(
      week: 14,
      trimester: 2,
      babySizeFruit: 'Peach',
      babySizeComparison: 'Size of a sweet ripe peach (~8.7cm)',
      estimatedLengthCm: 8.7,
      estimatedWeightGrams: 43.0,
      fetalMilestone: 'Soft lanugo hair carpets body; kidneys excrete urine into amniotic sac.',
      maternalChanges: 'Appetite returns with vitality; small baby bump begins to show.',
      clinicalTip: 'Prioritize lean proteins and iron-rich lentils to support red cell production.',
    ),
    15: const GestationalWeekInfo(
      week: 15,
      trimester: 2,
      babySizeFruit: 'Apple',
      babySizeComparison: 'Size of a crisp red apple (~10.1cm)',
      estimatedLengthCm: 10.1,
      estimatedWeightGrams: 70.0,
      fetalMilestone: 'Skeleton hardens into bone; baby perceives light differences through eyelids.',
      maternalChanges: 'Nasal congestion and sensitive gums due to increased blood flow.',
      clinicalTip: 'Use a saline nasal rinse and soft-bristled toothbrush to protect sensitive tissues.',
    ),
    16: const GestationalWeekInfo(
      week: 16,
      trimester: 2,
      babySizeFruit: 'Avocado',
      babySizeComparison: 'Size of a creamy avocado (~11.6cm)',
      estimatedLengthCm: 11.6,
      estimatedWeightGrams: 100.0,
      fetalMilestone: 'Heart pumps ~25 quarts of blood per day; scalp hair pattern established.',
      maternalChanges: 'Pregnancy "glow" develops from increased cutaneous vascular perfusion.',
      clinicalTip: 'Sleep comfortably on your left side to maximize placental blood flow.',
    ),
    17: const GestationalWeekInfo(
      week: 17,
      trimester: 2,
      babySizeFruit: 'Pomegranate',
      babySizeComparison: 'Size of a pomegranate (~13.0cm)',
      estimatedLengthCm: 13.0,
      estimatedWeightGrams: 140.0,
      fetalMilestone: 'Vernix caseosa protective barrier shields delicate skin from amniotic fluid.',
      maternalChanges: 'Round ligament stretches causing occasional quick twinges in the groin.',
      clinicalTip: 'Move slowly when standing up from seated or lying positions.',
    ),
    18: const GestationalWeekInfo(
      week: 18,
      trimester: 2,
      babySizeFruit: 'Bell Pepper',
      babySizeComparison: 'Size of a crisp bell pepper (~14.2cm)',
      estimatedLengthCm: 14.2,
      estimatedWeightGrams: 190.0,
      fetalMilestone: 'Inner ear bones ossify: baby can hear mother’s heartbeat, voice, and gut sounds.',
      maternalChanges: 'First "quickening" kicks and flutter sensations felt by mother!',
      clinicalTip: 'Talk and play soothing acoustic music; baby is actively listening.',
    ),
    19: const GestationalWeekInfo(
      week: 19,
      trimester: 2,
      babySizeFruit: 'Mango',
      babySizeComparison: 'Size of a golden mango (~15.3cm)',
      estimatedLengthCm: 15.3,
      estimatedWeightGrams: 240.0,
      fetalMilestone: 'Sensory neural centers specialize for taste, smell, touch, sound, and sight.',
      maternalChanges: 'Mild low-back discomfort as abdominal center of gravity shifts forward.',
      clinicalTip: 'Invest in a comfortable maternal supportive pillow for nighttime hip alignment.',
    ),
    20: const GestationalWeekInfo(
      week: 20,
      trimester: 2,
      babySizeFruit: 'Banana',
      babySizeComparison: 'Length of a whole banana (~25.6cm)',
      estimatedLengthCm: 25.6,
      estimatedWeightGrams: 300.0,
      fetalMilestone: 'Halfway mark! Anatomy scan confirms all 4 cardiac chambers and brain symmetry.',
      maternalChanges: 'Uterus reaches belly button (umbilicus) height.',
      clinicalTip: 'Celebrate reaching the midpoint of your pregnancy journey!',
    ),
    21: const GestationalWeekInfo(
      week: 21,
      trimester: 2,
      babySizeFruit: 'Carrot',
      babySizeComparison: 'Length of a garden carrot (~26.7cm)',
      estimatedLengthCm: 26.7,
      estimatedWeightGrams: 360.0,
      fetalMilestone: 'Bone marrow begins producing red blood cells; steady sleep/wake cycles.',
      maternalChanges: 'Leg cramps may occur at night; gentle calf stretches help immediately.',
      clinicalTip: 'Boost magnesium and potassium intake with bananas, spinach, and sweet potatoes.',
    ),
    22: const GestationalWeekInfo(
      week: 22,
      trimester: 2,
      babySizeFruit: 'Papaya',
      babySizeComparison: 'Size of a golden papaya (~27.8cm)',
      estimatedLengthCm: 27.8,
      estimatedWeightGrams: 430.0,
      fetalMilestone: 'Sense of touch refined; baby playfully grasps the umbilical cord and face.',
      maternalChanges: 'Slight physiological swelling in feet and ankles after standing.',
      clinicalTip: 'Elevate your feet on a footstool when resting during the workday.',
    ),
    23: const GestationalWeekInfo(
      week: 23,
      trimester: 2,
      babySizeFruit: 'Grapefruit',
      babySizeComparison: 'Size of a large grapefruit (~28.9cm)',
      estimatedLengthCm: 28.9,
      estimatedWeightGrams: 500.0,
      fetalMilestone: 'Rapid eye movement (REM) sleep begins; respiratory diaphragmatic practice.',
      maternalChanges: 'Linea nigra (pigmented line) may appear on the center of the abdomen.',
      clinicalTip: 'Stay shielded from direct harsh UV sun to prevent chloasma / melasma.',
    ),
    24: const GestationalWeekInfo(
      week: 24,
      trimester: 2,
      babySizeFruit: 'Cantaloupe',
      babySizeComparison: 'Size of a sweet cantaloupe (~30.0cm)',
      estimatedLengthCm: 30.0,
      estimatedWeightGrams: 600.0,
      fetalMilestone: 'Viability milestone reached; pulmonary branches and surfactant cells develop.',
      maternalChanges: 'Glucose screening challenge test is generally conducted between weeks 24-28.',
      clinicalTip: 'Complete your glucose screening test to rule out gestational diabetes.',
    ),
    25: const GestationalWeekInfo(
      week: 25,
      trimester: 2,
      babySizeFruit: 'Cauliflower',
      babySizeComparison: 'Size of a fresh cauliflower (~34.6cm)',
      estimatedLengthCm: 34.6,
      estimatedWeightGrams: 660.0,
      fetalMilestone: 'Capillaries fill with blood giving skin a healthy pink hue; responds to voices.',
      maternalChanges: 'Mild heartburn or acid reflux may occur after heavy meals.',
      clinicalTip: 'Avoid lying down within 90 minutes of eating dinner.',
    ),
    26: const GestationalWeekInfo(
      week: 26,
      trimester: 2,
      babySizeFruit: 'Romaine Lettuce',
      babySizeComparison: 'Length of a romaine lettuce head (~35.6cm)',
      estimatedLengthCm: 35.6,
      estimatedWeightGrams: 760.0,
      fetalMilestone: 'Eyes flutter open for the first time; distinct acoustic startle reflex.',
      maternalChanges: 'Blood pressure reaches its lowest mid-pregnancy nadir; stay hydrated.',
      clinicalTip: 'Practice pelvic tilts to maintain spine posture and relieve lower back pressure.',
    ),
    27: const GestationalWeekInfo(
      week: 27,
      trimester: 2,
      babySizeFruit: 'Rutabaga',
      babySizeComparison: 'Size of a sturdy rutabaga (~36.6cm)',
      estimatedLengthCm: 36.6,
      estimatedWeightGrams: 875.0,
      fetalMilestone: 'Final week of the Second Trimester! Complex brain wave patterns active.',
      maternalChanges: 'Shortness of breath as the growing uterus pushes upward against diaphragm.',
      clinicalTip: 'Take slow, deep diaphragmatic breaths and slow your walking pace.',
    ),
    28: const GestationalWeekInfo(
      week: 28,
      trimester: 3,
      babySizeFruit: 'Eggplant',
      babySizeComparison: 'Size of a large glossy eggplant (~37.6cm)',
      estimatedLengthCm: 37.6,
      estimatedWeightGrams: 1000.0,
      fetalMilestone: 'Third Trimester begins! Baby weighs ~1 kilogram and blinks actively.',
      maternalChanges: 'Prenatal appointments shift from monthly to every 2 weeks.',
      clinicalTip: 'If Rh-negative, Rhogam injection is typically administered at 28 weeks.',
    ),
    29: const GestationalWeekInfo(
      week: 29,
      trimester: 3,
      babySizeFruit: 'Butternut Squash',
      babySizeComparison: 'Size of a butternut squash (~38.6cm)',
      estimatedLengthCm: 38.6,
      estimatedWeightGrams: 1150.0,
      fetalMilestone: 'Massive brain cortex folding; baby absorbs ~250mg of maternal calcium daily.',
      maternalChanges: 'Braxton Hicks practice contractions may occur sporadically.',
      clinicalTip: 'Drink a glass of cold water and rest on your side if contractions occur.',
    ),
    30: const GestationalWeekInfo(
      week: 30,
      trimester: 3,
      babySizeFruit: 'Cabbage',
      babySizeComparison: 'Size of a round green cabbage (~39.9cm)',
      estimatedLengthCm: 39.9,
      estimatedWeightGrams: 1320.0,
      fetalMilestone: 'Amniotic fluid volume peaks; bone marrow fully oversees blood production.',
      maternalChanges: 'Sleep interruptions from frequent position shifts and bathroom visits.',
      clinicalTip: 'Wind down with a warm bath and limit evening liquids 1 hour before bed.',
    ),
    31: const GestationalWeekInfo(
      week: 31,
      trimester: 3,
      babySizeFruit: 'Coconut',
      babySizeComparison: 'Size of a heavy coconut (~41.1cm)',
      estimatedLengthCm: 41.1,
      estimatedWeightGrams: 1500.0,
      fetalMilestone: 'Major growth spurt: baby turns head side-to-side and tracks daylight.',
      maternalChanges: 'Colostrum (first breast milk) may occasionally leak from breasts.',
      clinicalTip: 'Pack soft breast pads if noticing early colostrum leakage.',
    ),
    32: const GestationalWeekInfo(
      week: 32,
      trimester: 3,
      babySizeFruit: 'Jicama',
      babySizeComparison: 'Size of a crisp jicama root (~42.4cm)',
      estimatedLengthCm: 42.4,
      estimatedWeightGrams: 1700.0,
      fetalMilestone: 'All 5 senses fully functional; toenails and fingernails fully grown.',
      maternalChanges: 'Skin over the belly feels tight and taut; apply soothing moisturizer.',
      clinicalTip: 'Massage natural shea butter or sweet almond oil onto abdominal skin.',
    ),
    33: const GestationalWeekInfo(
      week: 33,
      trimester: 3,
      babySizeFruit: 'Pineapple',
      babySizeComparison: 'Size of a sweet pineapple (~43.7cm)',
      estimatedLengthCm: 43.7,
      estimatedWeightGrams: 1900.0,
      fetalMilestone: 'Maternal antibodies pass across placenta, furnishing critical newborn immunity.',
      maternalChanges: 'Pelvis begins slowly widening and relaxing due to the relaxin hormone.',
      clinicalTip: 'Review your labor and birth preferences with your obstetrician or midwife.',
    ),
    34: const GestationalWeekInfo(
      week: 34,
      trimester: 3,
      babySizeFruit: 'Cantaloupe Melon',
      babySizeComparison: 'Size of a heavy melon (~45.0cm)',
      estimatedLengthCm: 45.0,
      estimatedWeightGrams: 2150.0,
      fetalMilestone: 'Lungs and central nervous system reach near-complete maturity.',
      maternalChanges: 'Fatigue returns comparable to first trimester; prioritize afternoon naps.',
      clinicalTip: 'Pack your hospital birth bag with essentials, chargers, and newborn clothes.',
    ),
    35: const GestationalWeekInfo(
      week: 35,
      trimester: 3,
      babySizeFruit: 'Honeydew Melon',
      babySizeComparison: 'Size of a honeydew melon (~46.2cm)',
      estimatedLengthCm: 46.2,
      estimatedWeightGrams: 2380.0,
      fetalMilestone: 'Kidneys fully mature; liver processes metabolic waste effectively.',
      maternalChanges: 'Group B Strep (GBS) swab screening is scheduled around weeks 35-37.',
      clinicalTip: 'Perform daily fetal kick counts: count 10 movements within a 2-hour window.',
    ),
    36: const GestationalWeekInfo(
      week: 36,
      trimester: 3,
      babySizeFruit: 'Swiss Chard',
      babySizeComparison: 'Length of a Swiss chard bunch (~47.4cm)',
      estimatedLengthCm: 47.4,
      estimatedWeightGrams: 2620.0,
      fetalMilestone: 'Baby descends into vertex (head-down) position into the maternal pelvis.',
      maternalChanges: '"Lightening" occurs: breathing eases as baby drops, but bladder pressure rises.',
      clinicalTip: 'Prenatal appointments increase to weekly visits until birth.',
    ),
    37: const GestationalWeekInfo(
      week: 37,
      trimester: 3,
      babySizeFruit: 'Winter Leek',
      babySizeComparison: 'Length of a winter leek (~48.6cm)',
      estimatedLengthCm: 48.6,
      estimatedWeightGrams: 2860.0,
      fetalMilestone: 'Early Term milestone! Pulmonary surfactant production is fully autonomous.',
      maternalChanges: 'Cervix begins effacing (thinning) and may start slight early dilation.',
      clinicalTip: 'Ensure your newborn car seat is safely inspected and installed in your vehicle.',
    ),
    38: const GestationalWeekInfo(
      week: 38,
      trimester: 3,
      babySizeFruit: 'Rhubarb',
      babySizeComparison: 'Length of crisp rhubarb stalks (~49.8cm)',
      estimatedLengthCm: 49.8,
      estimatedWeightGrams: 3080.0,
      fetalMilestone: 'Firm grasp reflex; sheds majority of vernix coating into amniotic fluid.',
      maternalChanges: 'Pelvic pressure increases; nesting instinct and home organization surge.',
      clinicalTip: 'Save provider emergency triage phone numbers into your speed dial.',
    ),
    39: const GestationalWeekInfo(
      week: 39,
      trimester: 3,
      babySizeFruit: 'Mini Watermelon',
      babySizeComparison: 'Size of a compact watermelon (~50.7cm)',
      estimatedLengthCm: 50.7,
      estimatedWeightGrams: 3290.0,
      fetalMilestone: 'Full Term reached! Brain and reflexes perfectly coordinated for life outside.',
      maternalChanges: 'Mucus plug may pass; watch for regular 5-1-1 contraction intervals.',
      clinicalTip: 'Remember the 5-1-1 rule: contractions 5 mins apart, lasting 1 min, for 1 hour.',
    ),
    40: const GestationalWeekInfo(
      week: 40,
      trimester: 3,
      babySizeFruit: 'Full-Term Watermelon',
      babySizeComparison: 'Size of a sweet summer watermelon (~51.2cm)',
      estimatedLengthCm: 51.2,
      estimatedWeightGrams: 3460.0,
      fetalMilestone: 'Due Date arrival! Baby is completely prepared to enter the world.',
      maternalChanges: 'Labor onset imminent; cervix fully ripening and effacing.',
      clinicalTip: 'Rest deeply, trust your body’s wisdom, and prepare to welcome your baby!',
    ),
  };

  /// Returns medical-grade gestational details for any week 1 through 40.
  static GestationalWeekInfo getWeekInfo(int week) {
    final clamped = week.clamp(1, 40);
    return _data[clamped] ?? _data[40]!;
  }
}
